### ISSUE TITLE
The index.js path specified in main of package.json is incorrect

### ISSUE THREAD

**Issue by HiroyukiNIshimura** [luislobo/sails-hook-responsetime#2]
(node:2778) [DEP0128] DeprecationWarning: Invalid 'main' field in '/app/BackDirect/node_modules/sails-hook-responsetime/package.json' of 'lib/index.js'. Please either fix that or report it to the module author
(Use `node --trace-deprecation ...` to show where the warning was created)

**Comment by luislobo** [comment]
@HiroyukiNIshimura thank you, noticed it also myself. Just fixed it in the latest version
